name: Validate Terraform

on:
  pull_request:
    branches: [release,development]
  push:
    branches: [release,development]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0

      - name: Init Terraform code
        run: terraform init

      - name: Validate Terraform code
        run: terraform validate
