name: Validate Terraform with tfsec

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform and TFSec
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0
          install_terraform_tools: true

      - name: Validate Terraform Code
        run: terraform validate

      - name: Run TFSec security scan
        run: tfsec .
